# Generated by Django 4.2.24 on 2025-09-21 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=64, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight_lbs', models.IntegerField(blank=True, null=True, verbose_name='Weight in pounds')),
                ('height_in', models.IntegerField(blank=True, null=True, verbose_name='Height in inches')),
                ('waist_in', models.IntegerField(blank=True, null=True, verbose_name='Waist in inches')),
                ('resting_heart_rate_bpm', models.IntegerField(blank=True, null=True, verbose_name='Resting Heart Rate BPM')),
                ('blood_pressure_mmhg', models.IntegerField(blank=True, null=True, verbose_name='Blood Pressure mmHg')),
                ('meds', models.TextField(blank=True, null=True, verbose_name='Medications')),
                ('doctor_release', models.BooleanField(default=False, verbose_name="Has a doctor's release?")),
                ('medical_history_risks', models.TextField(blank=True, null=True, verbose_name='Medical History and Risk Factors')),
                ('ambulatory', models.BooleanField(default=True, verbose_name='Can stand to work out?')),
                ('goals_incentives', models.TextField(blank=True, null=True, verbose_name='Goals and Incentives')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('warmups', models.TextField(blank=True, null=True, verbose_name='Warmups')),
                ('large_muscle_group_exercises', models.TextField(blank=True, null=True, verbose_name='Large Muscle Group Exercises')),
                ('small_muscle_group_exercises', models.TextField(blank=True, null=True, verbose_name='Small Muscle Group Exercises')),
                ('cooldowns', models.TextField(blank=True, null=True, verbose_name='Cooldowns and Stretches')),
                ('other_notes', models.TextField(blank=True, null=True, verbose_name='Accommodations and Other Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.client')),
            ],
        ),
    ]
