# Generated by Django 4.2.24 on 2025-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ambulatory',
            field=models.BooleanField(default=False, verbose_name='Can stand to work out?'),
        ),
    ]
