# Generated by Django 4.2.24 on 2025-09-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_client_ambulatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
